services:
  trading_db:
    container_name: trading
    image: postgres:latest
    volumes:
      - trading_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${TRADING_DB}
      - POSTGRES_USER=${TRADING_USER}
      - POSTGRES_PASSWORD=${TRADING_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d trading_db" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
  envio-indexer:
    container_name: envio-indexer
    image: hasura/graphql-engine
    depends_on:
      - trading_db
    ports:
      - '4100:4100'
    environment:
      - ENVIO_PG_USER=${ENVIO_PG_USER}
      - ENVIO_PG_PASSWORD=${ENVIO_PG_PASSWORD}
      - ENVIO_PG_DATABASE=${ENVIO_PG_DATABASE}
      - DATABASE_URL=${DATABASE_URL}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d trading_db" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: on-failure
    ports:
      - "1313:9000"  # Portainer UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  trading_data:
  portainer_data:
  envio_data: