# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio
networks:
- id: 11155111
  start_block: 0
  contracts:
  - name: deposit
    # abi_file_path: ../frontend/contracts/deposit.json
    address:
    - 0x4b39Eb5506E6BaB0085387504f3e0A05F2DdD0F1
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(address indexed user, address indexed token, uint256 amount)
      field_selection:
        transaction_fields:
          - hash
unordered_multichain_mode: true
preload_handlers: true
