# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio
networks:
- id: 11155111
  start_block: 0
  contracts:
  - name: deposit
    # abi_file_path: ../bacend/contracts/deposit.json
    address:
    - 0xA6c4d6F4d8e77b8479C0121fA035A65FbB951b2d
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(address indexed user, address indexed token, uint256 amount)
unordered_multichain_mode: true
preload_handlers: true
